---
deployment:
  tasks:
    - export DEPLOYPATH=/home/batiktv1/public_html/
    - /bin/cp -R public/admin $DEPLOYPATH
    - /bin/cp -R public/home $DEPLOYPATH

    - export DEPLOYPATH2=/home/batiktv1/batiktv_core/app/
    - /bin/cp -R app/Controllers $DEPLOYPATH2
    - /bin/cp -R app/Database $DEPLOYPATH2
    - /bin/cp -R app/Filters $DEPLOYPATH2
    - /bin/cp -R app/Helpers $DEPLOYPATH2
    - /bin/cp -R app/Models $DEPLOYPATH2
    - /bin/cp -R app/Views $DEPLOYPATH2

    - export DEPLOYPATH3=/home/batiktv1/batiktv_core/app/Config/
    - /bin/cp -R Routes $DEPLOYPATH3
