---
deployment:
  tasks:
    - export DEPLOYPATH=/home/batiktv1/public_html/
    - /bin/cp -R public_html/admin $DEPLOYPATH
    - /bin/cp -R public_html/home $DEPLOYPATH

    - export DEPLOYPATH2=/home/batiktv1/batiktv_core/app/
    - /bin/cp -R Controllers $DEPLOYPATH2
    - /bin/cp -R Database $DEPLOYPATH2
    - /bin/cp -R Filters $DEPLOYPATH2
    - /bin/cp -R Helpers $DEPLOYPATH2
    - /bin/cp -R Models $DEPLOYPATH2
    - /bin/cp -R Views $DEPLOYPATH2
